Ext.define 'YABSCA.view.organization.Tree',
  extend: 'Ext.tree.Panel'
  alias: 'widget.organization_tree'
  initComponent: ->
    Ext.apply this,
      store: 'Organizations'
      useArrows: true
      frame: true
    @callParent arguments
